### ISSUE TITLE
Nothing really here

### ISSUE THREAD

**Issue by ahhh** [propervillain/moistpetal#2]
Is there a real release somewhere else or something?

**Comment by kernel-sanders** [comment]
https://youtu.be/BqD6SP23470?t=101

1:41

**Comment by ahhh** [comment]
Thanks man! I hadn't seen that talk. Hilariously, I actually did that same wireless pen test he mentioned at the beginning of the talk and got in ¯\_(ツ)_/¯

**Comment by kernel-sanders** [comment]
https://twitter.com/BlacksunLabs_/status/1116760785269641217
